### ISSUE TITLE
Crash w/ Midnight & Endergetic

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/WorldBlender#6] opened 2020-04-02 14:49 UTC
`Minecraft v1.15.2`
`Forge v31.1.30`
`World Blender v1.3.3`
[`The Midnight v0.5.3`](https://www.curseforge.com/minecraft/mc-mods/the-midnight)
[`The Endergetic Expansion v1.2.5`](https://www.curseforge.com/minecraft/mc-mods/endergetic)

After a couple of minutes inside the World Blender world, I got this crash. From what I can gather from the crash report, it seems to be related to a Puff Bug from Endergetic Expansion interacting with the Suavis block from Midnight. The Nightstag from Midnight is already blacklisted.
[Crash Report](https://gist.github.com/WenXin20/1d1c0482c121d652d56c16d4bbf6fde9)
[Latest.log](https://gist.github.com/WenXin20/d30ed3277d4b7b8bdcee6c7810b83e7f)

**Comment by TelepathicGrunt** [comment] 2020-04-02 18:06
Thank you for reporting this! It seem this is an issue between The Endergetic Expansion and the Midnight with Puff Bug's pathfinding. 

I opened an issue report with TEE here that you can watch to see if progress is made on fixing this crash. If it's on the Midnight's end, they will tell me and I'll open an issue with The Midnight. https://github.com/minecraftabnormals/The-Endergetic-Expansion/issues/28

For now, you could blacklist the puff bug so it doesn't spawn and crashes the game until one of those two mods makes a patch to fix the issue. :)

**Comment by WenXin20** [comment] 2020-04-02 18:37
Thanks, I thought that might be the case since, those two mods don't usually interact since they are two separate dimensions.

**Comment by TelepathicGrunt** [comment] 2020-04-02 21:23
Turns out the issue is on The Midnight's side. I made an issue report to them here: https://github.com/Cryptic-Mushroom/The-Midnight/issues/372

Hopefully it will be fixed soon! I'll leave this issue report up so other people coming here to report the crash will see this thread and know a fix is coming.

**Comment by TelepathicGrunt** [comment] 2020-04-04 17:03
The Midnight just released a fix for this crash and is available here: https://www.curseforge.com/minecraft/mc-mods/the-midnight/files/2920964

I'll close this issue now as the problem is now gone!

**Closed as completed by TelepathicGrunt** 2020-04-04 17:03 UTC
Labels: bug

**Comment by WenXin20** [comment] 2020-04-04 17:16
Thanks for the help!
