### ISSUE TITLE
Conflicts with newest Xaero's minimap(1.14.4)

### ISSUE THREAD

**Issue by Litttlefish** [TelepathicGrunt/WorldBlender#1] opened 2020-03-13 13:59 UTC
![image](https://user-images.githubusercontent.com/38809254/76627323-c5a93080-6575-11ea-87c0-e8f7301fb0b8.png)
If start with it and the game will show this

**Comment by TelepathicGrunt** [comment] 2020-03-13 15:27
I just tested with 
`Xaeros_Minimap_20.5.2_Forge_1.14.4.jar`
`world_blender-1.14.4-1.2.1.jar`
and I was unable to reproduce that issue. 

Are you using v20.5.2 Xaeros Minimap (got this from Xaeros's site) and were you testing with any other mod on as well? (If so, what other mods were on?)

**Comment by Litttlefish** [comment] 2020-03-14 02:07
sry for late reply

it will happen with latest Xaero's worldmap and Xaeros Minimap together

**Comment by TelepathicGrunt** [comment] 2020-03-14 11:44
Hmm. I am still unable to reproduce the issue. 
![image](https://user-images.githubusercontent.com/40846040/76681233-46444d00-65c7-11ea-924f-66e4cb0b61e7.png)

Here is what I am using so far:
`XaerosWorldMap_1.5.6_Forge_1.14.4.jar`
`Xaeros_Minimap_20.5.2_Forge_1.14.4.jar`
`world_blender-1.14.4-1.2.1.jar`

And I am using 1.14.4 - 28.2.3 Forge (The very latest Forge version for 1.14.4)

Can you cause the bug one more time and then give me the crashlog file? or Latest.log file? That should help us narrow down the issue more. :)

**Comment by Litttlefish** [comment] 2020-03-15 04:55
[15三月2020 12:54:36.161] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Litttle_fish, --version, 1.14.4-forge-28.2.1, --gameDir, C:\Users\admin\AppData\Roaming\.minecraft\versions\1.14.4-forge-28.2.1, --assetsDir, C:\Users\admin\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 87df0c27824b47adbefa7c7ca33284a6, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.1, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[15三月2020 12:54:36.173] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_51 by Oracle Corporation
[15三月2020 12:54:36.652] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[15三月2020 12:54:37.919] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.4-forge-28.2.1, --gameDir, C:\Users\admin\AppData\Roaming\.minecraft\versions\1.14.4-forge-28.2.1, --assetsDir, C:\Users\admin\AppData\Roaming\.minecraft\assets, --uuid, 87df0c27824b47adbefa7c7ca33284a6, --username, Litttle_fish, --assetIndex, 1.14, --accessToken, ????????, --userType, mojang, --versionType, release]
[15三月2020 12:54:39.874] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Litttle_fish
[15三月2020 12:54:47.334] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.2 build 10
[15三月2020 12:54:49.424] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[15三月2020 12:54:50.043] [modloading-worker-3/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 28.2.1, for MC 1.14.4 with MCP 20190829.143755
[15三月2020 12:54:50.059] [modloading-worker-3/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v28.2.1 Initialized
[15三月2020 12:54:50.985] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: world_blender, class net.telepathicgrunt.worldblender.WorldBlender
java.lang.ClassFormatError: Duplicate field name&signature in class file net/minecraft/world/chunk/Chunk
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:129) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2911) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2917) ~[?:1.8.0_51]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:69) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$2160/1338770333.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) [?:28.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2097/472114025.accept(Unknown Source) [?:28.2]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2096/208824749.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2096/208824749.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2147/818905291.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[15三月2020 12:54:51.041] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[15三月2020 12:54:51.042] [Client thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1988/130326586.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.1.jar:28.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$393/248487859.call(Unknown Source) [forge-1.14.4-28.2.1.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
[15三月2020 12:54:52.687] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[15三月2020 12:54:57.377] [Thread-1/FATAL] [net.minecraftforge.common.ForgeConfig/CORE]: Forge config just got changed on the file system!
[15三月2020 12:54:57.473] [Server-Worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\admin\AppData\Roaming\.minecraft\versions\1.14.4-forge-28.2.1\config\world_blender-common.toml is not correct. Correcting
[15三月2020 12:54:57.587] [Server-Worker-2/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[15三月2020 12:54:57.587] [Server-Worker-2/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[15三月2020 12:54:57.610] [Server-Worker-2/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1988/130326586.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2363/1343957354.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1988/130326586.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[15三月2020 12:54:59.409] [Server-Worker-2/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'minecraft:blockstates/kelp.json' in resourcepack: 'Texture Improvments 1.13+' for variant: 'normal': Unknown blockstate property: 'normal'
[15三月2020 12:55:01.127] [Server-Worker-1/ERROR] [net.minecraft.client.renderer.texture.AtlasTexture/]: Using missing texture, unable to load minecraft:textures/block/command_block_minecart.png : java.io.FileNotFoundException: minecraft:textures/block/command_block_minecart.png
[15三月2020 12:55:01.376] [Server-Worker-2/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[15三月2020 12:55:01.377] [Server-Worker-2/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[15三月2020 12:55:01.377] [Server-Worker-2/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1988/130326586.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:136) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2365/878217617.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[15三月2020 12:55:01.669] [Client thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[15三月2020 12:55:01.670] [Client thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[15三月2020 12:55:01.875] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512 textures-atlas
[15三月2020 12:55:02.731] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/particle-atlas
[15三月2020 12:55:02.733] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/painting-atlas
[15三月2020 12:55:02.733] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128 textures/mob_effect-atlas
 here
forge version is 28.2.1

**Comment by TelepathicGrunt** [comment] 2020-03-15 12:46
I have a gut feeling of what is going on but lets find out if it is right. Where did you download my mod and xaeros mods from? Like the actual source that you got the mods from?

**Comment by Litttlefish** [comment] 2020-03-16 04:19
your mod is from curseforge

and forge is from its official website

xaero's mods from theirs official website

**Comment by TelepathicGrunt** [comment] 2020-03-16 23:47
Well, I tried some more and I still am not able to reproduce this crash that you are experiencing. I even ask other modders and no one seems to have any idea on what is causing this. Sorry. :(

I wish I could help you out but I got nothing. I'll keep this issue open so if anyone else gets the same issue, they can add their details to this report and I can start looking for similarities between the crashlogs and settings.

**Comment by Litttlefish** [comment] 2020-03-22 07:02
hmm strange
i mean
i used a brand new forge file and installed those 3 mods
but still appeared this issue

**Comment by TelepathicGrunt** [comment] 2020-06-19 22:10
Hmm. It’s been a while and it seems no one else is also having this issue. Really strange. I guess it was a one time thing so I’ll close this bug report now. Especially with me dropping 1.14 support since 1.16 is right around the corner

**Closed as completed by TelepathicGrunt** 2020-06-19 22:10 UTC
Labels: bug, help wanted, Unable To Reproduce
