### ISSUE TITLE
Loading Error w/ Lord of the Rings 

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/WorldBlender#9] opened 2020-06-03 21:37 UTC
`Minecraft v1.15.2`
`Forge v31.2.5`
[`Lord of the Rings v1.2.2`](https://lotrminecraftmod.fandom.com/wiki/Updates/Renewed)(under snapshot 1.2)

I get an error while loading the game if the mod Lord of the Rings is not blacklisted in the config.
[Crash Log](https://gist.github.com/WenXin20/d5ed375932d300e527d7981e93d17f78)
Error starts at `[16:16:41]`

![2020-06-03_16 27 20](https://user-images.githubusercontent.com/12000593/83691820-72fd7480-a5b8-11ea-8bfb-6b71b14806e3.png)

**Comment by TelepathicGrunt** [comment] 2020-06-03 23:46
Oh my. So much spam in that log that it got cut off lol. I'll try and reproduce the issue on my end as it seems to be an issue with how World Blender casts. Whoops!

Shouldn't take long. 

Also, is just Dimensional Dungeons and Resourceful Bees the only other mods crashing world blender or is these three what you found so far?

**Comment by WenXin20** [comment] 2020-06-04 00:04
Thanks!
Resourceful Bees crashes in the overworld as well, so it was unrelated to World Blender.

For Dimensional Dungeons, I was unable to reproduce the crash, although when first loading it, the log has an npe and says that code was called when the mod wasn't present, but the game still loads fine.

https://gist.github.com/WenXin20/f59533f914cc3c6164652fd9dc91cde9

**Comment by TelepathicGrunt** [comment] 2020-06-04 00:33
That dimensional dungeon issue is definitely an issue on my end. I had it write to the log if it fails setting up the mod compatibility with dimensional dungeons. time to find out why!

**Comment by TelepathicGrunt** [comment] 2020-06-04 00:39
Hmm. I just tried dimensional dungeons v1.06 and it didnt seem to cause that issue and the dungeons spawned in the world. What version of dimensional dungeons did you have on?

Also, looks like Resourceful bees has figured out their issue and their next update will fix their crash! https://github.com/Dungeon-Derps-Development/ResourcefulBees/issues/8

**Comment by WenXin20** [comment] 2020-06-04 00:46
I'm using version 1.06 as well, although I'm not sure if the Dungeons are spawning or not. How often do they spawn in World Blender? I just know that the error was printed in the logs.

**Comment by TelepathicGrunt** [comment] 2020-06-04 00:57
They spawn fairly frequently underground and can easily be found with Night Vision + Spectator mode.

But if that error is printed in the log, they definitely wont be spawning for you. Super odd.
Can you try again with this jar and give me the crashlog? Hopefully this will give me more info on what is causing the crash. I think i know what it is but I need to confirm
[world_blender-1.15.2-1.3.5b.zip](https://github.com/TelepathicGrunt/WorldBlender/files/4726874/world_blender-1.15.2-1.3.5b.zip)

**Comment by WenXin20** [comment] 2020-06-04 01:00
Sure! I'll give it a try later tonight

**Comment by TelepathicGrunt** [comment] 2020-06-04 02:55
Ok I am fairly certain I fixed the problem with this patch. I believe not all mods are registering their features (trees, ores, etc) properly and so, it crashes my code. When you do get a chance, try this jar instead of the other one and see if this fixes the problem. If so, I'll close this issue report and upload the working version to curseforge.
[world_blender-1.15.2-1.3.5c.zip](https://github.com/TelepathicGrunt/WorldBlender/files/4727196/world_blender-1.15.2-1.3.5c.zip)

Also, thank you for reporting all this! :)

**Comment by WenXin20** [comment] 2020-06-04 02:59
Thanks! I'll give it a try.

**Comment by WenXin20** [comment] 2020-06-04 05:18
It works with both mods! :)

**Comment by TelepathicGrunt** [comment] 2020-06-04 11:45
Perfect!
v1.3.5 is now up and approved on curseforge!
https://www.curseforge.com/minecraft/mc-mods/worldblender/files/2972270

**Closed as completed by TelepathicGrunt** 2020-06-04 11:45 UTC
Labels: bug
